server:
  port: 8083

spring:
  application:
    name: springboot-kafka-02

#kafka config
  kafka:
    bootstrap-servers: node1:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 163854
      buffer-memory: 33554432 #32MB = 32 * 1024 * 1024

    consumer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: springboot-consumer02
      auto-offset-reset: earliest #reset to earliest if cannot locate offset
      enable-auto-commit: true
      auto-commit-interval: 1000



