debug: true

server:
  port: 83

http-pool:
  max-total: 200
  default-max-per-route: 100
  connect-timeout: 5000
  connection-request-timeout: 1000
  socket-timeout: 65000
  validate-after-inactivity: 2000


#spring:
#  mvc:
#    static-path-pattern: /static/**

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mtravel_db
    username: root
    password: 630716
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 1000


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true


